# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eff254fdcda917eb00f05a5785cf042e61c00ed40de4d0e862fb46e4a2610f6267c535be2d79b3b663f35207c75aa639ef18931d25ab21956aab2e8d704b993

test:
  secret_key_base: e76d92fe6d86fa9b3cc163060e7b82470521cb35cab379359323cddf71ba8be3c84efda8cff47c498bcd13a53e3e4744d6cae978045816c70b109473253af311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
